services:
  postgres:
    container_name: antitail_postgres
    image: postgres:15.14-alpine3.22
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=antitail_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    container_name: antitail_pgadmin
    image: dpage/pgadmin4:9.9
    environment:
      PGADMIN_DEFAULT_EMAIL: root@local.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
